### PR TITLE
Quality of Life [Cursor, Text Widget] (10/25/20)

### PR DESCRIPTION
**Pull request by nmedovich**
Added a white cursor in the Text() widget under editor > __init__.py.  I wasn't able to determine if the text box was selected or not because its color matched the background.
The Text() widget remained less than 600x400 when I maximized the window.  Added "fill=BOTH', meaning X and Y.  Added "side=BOTTOM" to dock it to the bottom and make its resizes relative to the bottom.  Added "expand=True", which allows it to grow along whatever directions defined by 'fill' parameter.

### CODE REVIEW

**Comment by nmedovich** [comment]
In regards to the second PR
Lines 227-234 declare the Control-Key + <key> shortcuts.
I added a "Select-All" shortcut key, and the corresponding function.
The file-operation shortcut functions (save, open, new) were causing errors on my two test clients.  The function was providing 1 argument to the new_file(), saveCurrentFile(), and open() file functions, but they do not accept arguments.  So, I added a wrapper function for each that accepts one argument, and calls the related function.

If one is operating on a "new" file, and saves it, the name of the file (and path to it) is added to the title bar.  The same occurs on file Open.
If the user creates a new file, it will clear the contents of the title bar, and displays the contents of the new "base_title" variable, which currently hold the name of the software, per the original program (Lines 17, 20)

Cheers

**Review by Amazeryogo — CHANGES_REQUESTED** [review]
Nice, Thanks. Just one point, I would like to persist with the base_title as surf-exel (omitting the 'c' )

**Comment by nmedovich** [comment]
Whoops, I actually didn't mean to change that.
Pushed up another commit without the c in the base_url variable.

**Review by Amazeryogo — COMMENTED** [review]
looks great!

**Comment by Amazeryogo** [comment]
so should I merge it ?

**Comment by nmedovich** [comment]
It's up to you.  You could just leave the changes in my fork, but if you want them in the master, you'll have to merge.

**Comment by Amazeryogo** [comment]
did it , looks great to me!

**Comment by nmedovich** [comment]
Thank you very much :-)

**Comment by Amazeryogo** [comment]
You're welcome :-)

**Pull request merged**
